[package]
authors = ["IdanArye <idanarye@gmail.com>"]
name = "chapter-tracker"
version = "0.1.0"

[dependencies]
diesel_migrations = "1.3.0"

[dependencies.diesel]
features = ["sqlite"]
version = "1.3.2"

[dev-dependencies]
tempfile = "3.0.3"
